#!/bin/bash

# check root privileges
[ `id -u` != '0' ] && echo "Use sudo or su" && exit -1

# find initdb
INITDB=`find / -name initdb`
[ "$INITDB" != "/*initdb" ] && [ "$INITDB" = "" ] && echo "You have not postgresql installation" && exit -2

# initialize PGDATA
echo -n "Enter data directory full path [/data/postgres/12/data]: "
read PGDATA

[ "$PGDATA" != "/*" ] && [ "$PGDATA" = "" ] && PGDATA=/data/postgres/12/data

# create PGDATA
echo "PGDATA = ${PGDATA}"
mkdir -p $PGDATA
chown postgres:postgres $PGDATA
chmod -R 0644 $PGDATA

# change PGDATA in bash profile of postgres user

echo "[ -f /etc/profile ] && source /etc/profile" > '/var/lib/pgsql/.bash_profile'
echo "PGDATA=${PGDATA}" >> '/var/lib/pgsql/.bash_profile'
echo "export PGDATA" >> '/var/lib/pgsql/.bash_profile'


# initialize DB cluster
su -c "${INITDB} --pwprompt -D ${PGDATA}" postgres

# enter access subnet
echo -n "Enter subnet to access DB [192.168.0.0/24]: "
read subnet
[ "$subnet" = "" ] && subnet='192.168.0.0/24'

# add subnet on configuration
echo "host         all     all             ${subnet}                 md5" >> `find $PGDATA -name pg_hba.conf`
